# This file is part of 'nark'.
#
# 'nark' is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# 'nark' is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with 'nark'.  If not, see <http://www.gnu.org/licenses/>.

# Travis CI config.
#
#   https://travis-ci.org/hotoffthehamster/nark

language: python

# Specify xenial for 3.7 support.
dist: xenial

matrix:
  include:
    # Unit tests run on each Python version.
    - env: TOXENV=py37
      python: '3.7'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=py35
      python: '3.5'
    # Other tasks run against latest Python.
    - env: TOXENV=codecov
      python: '3.7'
    - env: TOXENV=dist_check
      python: '3.7'
    - env: TOXENV=docs
      python: '3.7'
    - env: TOXENV=flake8
      python: '3.7'

install:
  - pip install -U tox

script: tox

notifications:
  email: false

